# Basic docker compose file to run the copilot-usage-service app        lication

services:
  copilot-usage-service:
    build:
      context: .
      dockerfile: container/development/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - BILLING_PERIOD_ENDPOINT=https://owpublic.blob.core.windows.net/tech-task/messages/current-period
      - REPORT_ENDPOINT=https://owpublic.blob.core.windows.net/tech-task/reports
      - BASE_COST_PER_MESSAGE=1
      